language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  include:
    - php: 7.0
      env: PHPCS=1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit
  - if [[ $PHPCS = 1 ]]; then ./vendor/bin/phpcs --standard=PSR1,PSR2 src/; fi
  - if [[ $PHPCS = 1 ]]; then ./vendor/bin/phpcs --standard=PSR1,PSR2 tests/; fi
